### ISSUE TITLE
Question about Chlorine REPL & REBL

### ISSUE THREAD

**Issue by rlhk** [seancorfield/dot-clojure#5]
Hi I just followed your great dot-closure file and YouTube videos about Atom, Chlorine & REBL.
I can eval expressions in terminal repl, and result is sent to rebl well. 

I can connect Chlorine to the same repl server at same port 50505, however the evaluated expressions won't send to rebl at all. There seems no special config to make this work in your videos. What could be the possible issue? Thanks.

**Comment by seancorfield** [comment]
How did you start your REPL?

To get a Socker REPL, you need to use `-A:socket` on the `clj` command so it starts a Socket REPL as well as the regular REPL. You'll probably want `-A:test` as well so your `test` folder is on the classpath.

Optional: `-A:comp` -- adds additional auto-completion via the Compliment library (Chlorine can do auto-completion without this, but this makes things a bit more comprehensive).

**Comment by seancorfield** [comment]
It's also worth noting that to use the REBL integration, you must be running Clojure 1.10.0 or 1.10.1.

**Comment by rlhk** [comment]
I mimicked both your video introductions. The alias are copied from your dot-closure.

Here's my boring command history, all with the same issue not able to get Chlorine REPL to send result to REBL. Guess alias order doesn't matter. Yes, I'm with Clojure 1.10.1. + Java 8 + latest REBL freshly downloaded.

```
9950  clj -A:test:comp:socket:rebl-11
 9956  clj -A:test:comp:socket:rebl
 9957  clj -A:test:comp:socket:rebl-11
 9958  clj -A:test:rebl-11:socket
 9959  clj -A:test:comp:socket:rebl-11
 9979  clj -A:test:comp:socket:rebl-11
 9980  clj -A:test:comp:socket:rebl-8
 9983  clj -A:test:comp:socket:rebl-8
 9989  clj -A:test:comp:socket:rebl-8
 9992  clj -A:test:comp:socket:rebl-8
 9997  clj -A:test:comp:socket -R:rebl-8
 9998  clj -A:test:comp:socket:rebl-8
 9999  clj -A:comp:test:rebl-8:socket
10002  clj -A:comp:test:rebl-8:socket
10006  clj -A:socket
10007* clj -A:rebl-8
10008  clj -A:comp:test:rebl-11:socket
10011* clj -A:comp:test:rebl-11:socket
10014* clj -A:comp:test:rebl-8:socket
...
```

**Comment by seancorfield** [comment]
Two questions:

1. Are you actually getting the REBL UI up and running? (and you can enter expressions into REBL's REPL pane and evaluate them OK?)

2. Are you using the "inspect" commands from my `init.coffee` file rather than the "eval" commands that are bundled with Chlorine?

The built-in evaluate commands just run code in the REPL (not REBL). The inspect commands from my init file run the code _and_ submit the result (and the source form) to REBL for display.

**Comment by rlhk** [comment]
1. Yes. REBL UI is up and running and expressions in REBL's REPL evaluate good.
2. I'm using Chlorine's built-in evaluate commands. I'm not aware of your init.coffee. There's no mention of it in the videos. Where can I find it?

**Comment by rlhk** [comment]
Just found it: https://github.com/seancorfield/atom-chlorine-setup/blob/master/init.coffee
Will give it a shot and report back.

**Comment by rlhk** [comment]
The `init.coffee` setup works great. Thank you!
